name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - joblib=1.4.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.4
  - libffi=3.4.2
  - libhwloc=2.11.2
  - libiconv=1.17
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libsqlite=3.47.2
  - libxml2=2.13.5
  - libzlib=1.3.1
  - mkl=2024.2.2
  - numpy=1.26.4
  - openssl=3.4.0
  - pip=24.3.1
  - python=3.12.8
  - python_abi=3.12
  - scikit-surprise=1.1.4
  - scipy=1.15.1
  - setuptools=75.8.0
  - tbb=2021.13.0
  - tk=8.6.13
  - wheel=0.45.1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.8.0
      - click==8.1.8
      - colorama==0.4.6
      - fastapi==0.115.6
      - h11==0.14.0
      - idna==3.10
      - pandas==2.2.3
      - pyarrow==18.1.0
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.41.3
      - surprise==0.1
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uvicorn==0.34.0
